### ISSUE TITLE
New Azure Key Vault/Identity libraries

### ISSUE THREAD

**Issue by sopelt** [ryanjerskine/IdentityServer4.Contrib.KeyManagement.AzureKeyVault#1]
Hi, thanks for packaging these helpers! I am thinking of updating it to the new [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity) and [Azure.Security.KeyVault.Certificates](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates) & co. in order to be able to consistently use the new library versions.
Is that something you are interested in/are working on? I would prefer having an update to your existing package instead of creating a new one.

**Comment by ryanjerskine** [comment]
I should be able to work on an update and I'm more than willing to accept any PRs as well. I don't currently have anything in production using this so I'll have to wait until I have some time to spin up something to develop against.

**Comment by sopelt** [comment]
Thank you for the swift reply @ryanjerskine 
I'll take a look at the required changes  ;)

**Comment by sopelt** [comment]
@ryanjerskine I refactored the code/dependencies to use the new libraries while trying to not touch the rest of the code too much for now. (see #2 )

**Comment by ryanjerskine** [comment]
Closed by #2 thanks for the contribution!

**Comment by sopelt** [comment]
Thanks for the swift merge! Could you bump the version and update the published nuget package as well?

**Comment by ryanjerskine** [comment]
Sorry about that, didn't have AppVeyor set up 100% correctly. A new version should now be available.
